---
- name: chroot wrapper script
  copy:
    dest: /root/chroot_wrapper.sh
    src: files/chroot_wrapper.sh
    owner: 'root'
    mode: '0755'

- name: copy resolv.conf into chroot
  copy:
    src: /etc/resolv.conf
    dest: /mnt/gentoo/etc/resolv.conf
    remote_src: yes

- name: mount /proc in chroot
  command: mount --types proc /proc /mnt/gentoo/proc 
  
- name: mount /sys in chroot
  command: mount --rbind /sys /mnt/gentoo/sys 
  
- name: make-rslave /proc in chroot
  command: mount --make-rslave /mnt/gentoo/sys 
  
- name: mount /dev in chroot
  command: mount --rbind /dev /mnt/gentoo/dev 
  
- name: make-rslave /dev in chroot
  command: mount --make-rslave /mnt/gentoo/dev 
  
- name: mount /run in chroot
  command: mount --bind /run /mnt/gentoo/run 
  
- name: make-rslave /run in chroot
  command: mount --make-slave /mnt/gentoo/run 

- name: enable chroot wrapper
  set_fact:
    ansible_shell_executable: /root/chroot_wrapper.sh

