---
- name: configure sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    regexp: '^PermitRootLogin'

- name: start sshd at boot
  ansible.builtin.systemd_service:
    name: sshd
    enabled: true
- name: start systemd-networkd at boot
  ansible.builtin.systemd_service:
    name: systemd-networkd
    enabled: true
