---
- name: systemd-generate-machine-id
  command: systemd-machine-id-setup
- name: Create Network Config
  blockinfile:
    dest: /etc/systemd/network/wired.network
    content: |
      [Match]
      Name=*
      [Network]
      DHCP=yes

    owner: root
    mode: '0644'
    create: yes
